### ISSUE TITLE
web push project doesnt exist in this repo

### ISSUE THREAD

**Issue by touseefbsb** [dhananshan/PWA-Asp.NetCore#2]
web app references the web push project, but web push project doesnt actually exist in this repo that is why web app cannot even build

**Comment by dhananshan** [comment]
@touseefbsb  the web push project is in a different repo here: [https://github.com/dhananshan/web-push-csharp.netcore](url) . Its maintained separately because I temporarily upgraded the web push [https://github.com/web-push-libs/web-push-csharp](url) to support core 2.0 until the original author upgrades it. for the time being you can download and reference it in your project.

**Comment by touseefbsb** [comment]
oh ok thnks
